### ISSUE TITLE
[Question] Display and fan

### ISSUE THREAD

**Issue by Zesko** [dgroenen/lenovo-ideapad-pro-5-14-14APH8-120hz-fix#1]
Hi,

I am looking for this same laptop before purchasing. I still doubt it's good with Linux.

I think you have an experience with the device.

I have some questions:

* Can you verify if its display IPS 2880x1800 supports HDR (10-bit)?
* Is the fan too loud when charging the battery? (I've read some comments about fan curve issue)
I am not sure if the current BIOS firmware 2023-12-XX fixes this issue.
* Are there any other problems?

Thanks

**Comment by dgroenen** [comment]
**HDR**: I'm afraid I'm not sure how to verify this in Linux as I don't think my software stack supports it. I'm running a vanilla Debian Bookworm set-up with the exception of a mainline kernel. I'm also using Gnome on Wayland.

**Fan noise**: this is very subjective, but since I got the laptop the fan noise never caught my attention. I think it's very quiet. I don't think the fan behaves differently when charging the battery (or I never noticed). I've never updated the BIOS; `dmidecode` says I'm running rev 1.25 from 06/26/2023

**Other issues**: make sure to run kernel 6.7 or newer, earlier versions have issues with the amdgpu driver (sporadic crashes and hangs). Ever since 6.7-rc-something the amdgpu issues have been fixed. There is only one issue that sometimes hits me, and that is that a wake-up from suspend once in a while comes with a failed query of the real-time clock, causing the system date-time to be set decades into the future. I'm pretty sure it is this [kernel bug report](https://bugzilla.kernel.org/show_bug.cgi?id=217626) (I see the same kernel log entries whenever it happens). This is manageable by manually syncing the date-time whenever it happens.

All in all I'm very happy with the laptop and enjoy using is on a daily basis.
